# api-gateway-bff / k3d local overrides
replicaCount: 1
image:
  repository: "k3d-local-registry:5050/api-gateway-bff"
  tag: "latest"
  pullPolicy: Always
resources:
  requests: { cpu: "50m",  memory: "64Mi" }
  limits:   { cpu: "200m", memory: "128Mi" }
vault:
  enabled: false
