name: CI â€” order-service
on:
  push:
    paths: ["services/order-service/**", ".github/workflows/ci-order-service.yml"]
  pull_request:
    paths: ["services/order-service/**"]
env:
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
  ECR_REPOSITORY: ecommerce-eks/order-service
  IMAGE_TAG: ${{ github.sha }}
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/order-service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: "1.22" }
      - run: go vet ./...
      - run: go build ./...

  build-and-push:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}
      - uses: aws-actions/amazon-ecr-login@v2
      - working-directory: services/order-service
        run: docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
      - if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
